Bad parameter 'AU' passed in vector query for CVSS link
owtf/boilerplate-templates pull request #3
Opened 2017-04-10 20:26 UTC by csk

The link was incorrectly passing 'AU' instead of 'Au' parameter to the CVSS link.

Jekyll version I am using (jekyll 3.4.3) generates links as abs urls instead of reltative ones.

2017-04-10 20:39 UTC, csk commented
I just noted that there is some google analytics code being added. The script with the tracking code was already in the codebase but somehow wasn't included until now. I suppose it is my jekyll version. Review.

There is also a .gitignore ignoring _site/* but the files are already being tracked by git so they get comitted too. I think they should be removed from repo but don't know if they are needed by github pages.

2017-04-10 20:55 UTC, viyatb commented on README.md
> +1. Try out your changes to see if it is working as expected. Serve the project using `jekyll serve --baseurl=/boilerplate-templates`
You have two "1." indexes there. Please remove the second one.

2017-04-10 21:03 UTC, viyatb requested changes
You should have proper, meaningful commit messages.
Try combining the commits (you have 3!) into 1 commit which has a meaningful message.

2017-04-10 21:03 UTC, viyatb commented
@csk I'll remove the `_site` folder.

2017-04-11 15:42 UTC, merged

2017-04-11 15:42 UTC, viyatb commented
@csk thanks!